mkdir -p data/test/
echo -e "@SEQ_ID\nGATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAA\n+\nIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII" > data/test/sample1.fastq
echo -e "@SEQ_ID\nGATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAA\n+\nIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII" > data/test/sample2.fastq
